#pragma once

// Stub for clangd; real FreeRTOSConfig.h is generated by ESP-IDF build.

#define configMINIMAL_STACK_SIZE 768
#define configMAX_PRIORITIES 25
#define configNUM_CORES 1
#define configUSE_PREEMPTION 1
#define configUSE_IDLE_HOOK 0
#define configUSE_TICK_HOOK 0
#define configUSE_16_BIT_TICKS 0
#define configTICK_RATE_HZ 100
