esphome:
  name: mlx90614-test
  min_version: 2026.5.3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ..
    refresh: 0s
    components: [ mlx90614 ]

i2c:
  id: i2c_bus
  sda: GPIO35
  scl: GPIO36
  scan: false
  frequency: 100kHz

mlx90614:
  id: infrared_temperature
  i2c_id: i2c_bus
  address: 0x5A
  update_interval: 10s
  ambient:
    name: Ambient
  object:
    name: Object
  object2:
    name: Object 2
