esphome:
  name: esc-higher-test

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ..
    refresh: 0s
    components: [ esc_higher ]

i2c:
  id: i2c_bus
  sda: GPIO21
  scl: GPIO22
  frequency: 400kHz

esc_higher:
  id: esc
  i2c_id: i2c_bus
  update_interval: 100ms
  address: 0x34
  speed_ramp_target_rpm: 7200
  speed_ramp_time_ms: 750
  speed_target:
    name: "Speed Target"
  current_fault:
    name: "Current Fault"
  bus_voltage:
    name: "Bus Voltage"
  current:
    name: "Current"
  mechanical_speed:
    name: "Mechanical Speed"
  target_speed:
    name: "Target Speed"
  controller_temperature:
    name: "Controller Temperature"
