esphome:
  name: bq25756-test
  min_version: 2026.5.3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

substitutions:
  wifi_ssid: "compile-placeholder"
  wifi_password: "compile-placeholder"
  api_encryption_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
  ota_password: "compile-placeholder"

external_components:
  - source:
      type: local
      path: ..
    refresh: 0s
    components: [ bq25756 ]

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

api:
  encryption:
    key: "${api_encryption_key}"

ota:
  - platform: esphome
    password: "${ota_password}"

i2c:
  id: i2c_ext
  sda: GPIO35
  scl: GPIO36
  scan: true
  frequency: 400kHz

bq25756:
  id: charger
  i2c_id: i2c_ext
  address: 0x6B
  update_interval: 1s
  battery:
    cell_count: 4
    cell_chemistry: lithium_ion
  charging:
    battery_current_limit: 5A
    input_current_limit: 3A
  calibration:
    measured_battery_voltage:
      name: "Measured Battery Voltage"
    calibrate_feedback:
      name: "Calibrate Charger Feedback"
  measurements:
    input_current:
      name: "Charger Input Current"
    input_voltage:
      name: "Charger Input Voltage"
    battery_current:
      name: "Charger Output Current"
    battery_voltage:
      name: "Charger Output Voltage"
    temperature_percent:
      name: "Charger TS Percent"
  diagnostics:
    feedback_voltage:
      name: "Charger Feedback Voltage"
  status:
    charging:
      name: "Charge Status"
    temperature:
      name: "Charger TS Status"
    mppt:
      name: "Charger MPPT Status"
    faults:
      name: "Charger Status Flags"
  controls:
    charge_enable:
      name: "Charger Charge Enable"
    dump_registers:
      name: "Charger Dump Registers"
